name: Run Discord Bot

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # 수동으로 실행 가능

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # 최신 버전 사용

    - name: Set up Python
      uses: actions/setup-python@v5  # 최신 버전 사용
      with:
        python-version: '3.9'  # 원하는 Python 버전 (예: 3.9)

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run bot
      run: |
        python bot.py
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}  # GitHub Secrets에서 토큰 설정
